### ISSUE TITLE
Tarea: Infografía.

### ISSUE THREAD

**Issue by lourdeshernandez2003** [SistemasTecTlaxiaco/infografia-lourdeshernandez2003#3]
[sistemas NUMERICOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lourdeshernandez2003/files/7125500/sistemas.NUMERICOS.pdf)

**Comment by lourdeshernandez2003** [comment]
[sistemas NUMERICOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lourdeshernandez2003/files/7125515/sistemas.NUMERICOS.pdf)

**Comment by lucero012** [comment]
un 17% te falto enlaces bibliográficos

**Comment by josealfredo79** [comment]
si esta incompleto y debe evaluarse de acuerdo a la rubrica
